### ISSUE TITLE
獲取資訊失敗，請稍候再嘗試。 

### ISSUE THREAD

**Issue by UVJkiNTQ** [eric2788/bilibili-danmaku-inserter#2]
**描述问题**
获取弹幕发送者资讯 点击 后显示失败

![image](https://user-images.githubusercontent.com/12570945/205910892-cb9cf2c7-738d-4cd9-bdf0-7725dda39eaf.png)

**你的配置**
 - 浏览器 chrome
 - 使用的插件版本 bilibili danmaku inserter  0.4.3

**Comment by eric2788** [comment]
检查了一下发现是html元素被更改了的问题: https://github.com/eric2788/bilibili-danmaku-inserter/blob/fd1c3acb525468dcd6f765024ef44859747666f7/src/background.ts#L131

这个插件我太久没更新了 (~~因为感觉没人用~~)，所以我认为可能不止一处地方有问题，你之后能打开开发者模式直接装我的修复版本吗？我想看看有哪些地方会出问题

**Comment by eric2788** [comment]
试试这个版本: https://github.com/eric2788/bilibili-danmaku-inserter/suites/9711704405/artifacts/465576491

**Comment by UVJkiNTQ** [comment]
> 检查了一下发现是html元素被更改了的问题: https://github.com/eric2788/bilibili-danmaku-inserter/blob/fd1c3acb525468dcd6f765024ef44859747666f7/src/background.ts#L131
> 
> 这个插件我太久没更新了 (~~因为感觉没人用~~)，所以我认为可能不止一处地方有问题，你之后能打开开发者模式直接装我的修复版本吗？我想看看有哪些地方会出问题

嗯 我会直接开发模式载入测试。
感觉没人用可能是因为目前熟肉效率高了，都是好事.jpg

我的用途是给不放弹幕姬到直播页面的主播，给录播添加弹幕作为字幕。

**Comment by eric2788** [comment]
> > 检查了一下发现是html元素被更改了的问题: https://github.com/eric2788/bilibili-danmaku-inserter/blob/fd1c3acb525468dcd6f765024ef44859747666f7/src/background.ts#L131
> > 
> > 这个插件我太久没更新了 (~因为感觉没人用~)，所以我认为可能不止一处地方有问题，你之后能打开开发者模式直接装我的修复版本吗？我想看看有哪些地方会出问题
> 
> 嗯 我会直接开发模式载入测试。 感觉没人用可能是因为目前熟肉效率高了，都是好事.jpg
> 
> 我的用途是给不放弹幕姬到直播页面的主播，给录播添加弹幕作为字幕。

了解，不过如果以发送弹幕的形式，可能需时甚久，因为b站的发送弹幕间隔时间很不稳定，保守时间是十秒一次(大概？忘了)

另外测试版本如果没有问题也告诉我一下，没问题我就PR了

**Comment by UVJkiNTQ** [comment]
发送弹幕修好了。
不过确实间隔要挺长的，10s不行，15s比较稳。

**Comment by eric2788** [comment]
> 发送弹幕修好了。
> 不过确实间隔要挺长的，10s不行，15s比较稳。

那還有其他問題嗎

**Comment by UVJkiNTQ** [comment]
> > 发送弹幕修好了。
> > 不过确实间隔要挺长的，10s不行，15s比较稳。
> 
> 那還有其他問題嗎

暂时没有发现了。
